export type ProfileModel={
  Accept?: boolean
  Brand?: string
  Company?: string
  Country_Code?: string
  Date_Of_Birth?: string
  Description?: string
  DeviceType?: string
  Email: string
  First_Name: string
  Gender: string
  Id: number
  IsQRVerifiedByAdmin?: boolean
  IsQRVerifiedByClient?: boolean
  Job_Title?: string
  LOB_Location_Type_Id?: number
  Last_Name: string
  Loc_Name?: string
  Location_Id?: number
  MemberShip_Category_Name?: string
  MemberShip_Type_Name: string
  Member_Id: string
  Membership_Activation_Date: string
  Membership_Category_Id: number
  Membership_Type_Id: number
  Mobile_Number: string
  Model?: string
  NotificationToken?: string
  OS?: string
  Profile_Photo: string
  StatusUser?: boolean
  Uniquly_Identifier?: string
}
