export type WorkspaceBookingModel = {
  Id: number;
  Platform: string;
  Date_Time: any;
  First_Name: string;
  Last_Name: string;
  Country_Code: string;
  Mobile_Number: string;
  Plan_Day: number;
  End_Date: any;
  Mode: string;
  Credit_Hours: any;
  Amount: number;
  Payment_Method: number;
  Entry_Scan_Time: any;
  Opportunity_Start_Date: any;
  Status: string;
  Lounge_Client_Id: number;
  PlanDay_Type: string;
  Payment_Method_Name: string;
  Scan_Out: any;
  Scan_in: any;
  Location_Name: string;
  viewHrs?: string;
  LOB_Location_Type_Id: number;
  LOB_Location_Type_Name: string;
  Loc_Id: number;
  PlanDayName: string;
  lstReservation_Details: {
    End_DateTime: string;
    Id: number;
    Reservation_Transaction_Id: number;
    Start_DateTime: string;
  }[];
  lstTopupHistory: any[];
};
