import { IndustryModel } from './../../Industries.model';
export type ManageLocationModel = {
  Id: number;
  Loc_Name: string;
  Loc_District_ID: number;
  Loc_Address: string;
  Loc_BuildYear: number;
  Loc_Area_Gross: number;
  Loc_Area_Leasable: number;
  Loc_Map_Address: string;
  Loc_Contract_Length: number;
  Loc_Contract_Start_Date: string;
  Loc_Contract_End_Date: string;
  Loc_Payment_Terms_ID: number;
  Loc_Partentership_Type_ID: number;
  Loc_Monthly_Rent_Amount: number;
  Loc_Payment_Method: number;
  Loc_Estimated_Annualized_Amount: number;
  Loc_Estimated_Contract_Amount: number;
  Loc_Annual_Increase: number;
  CreatedBy: string;
  CreatedAt: string;
  LastModifiedBy: string;
  LastModifiedAt: string;
  Loc_MainCurrency: number;
  Commercial_Name: string;
  Phone: string;
  LOB_Location_Type_Id: number;
  Main_Currency_Name: string;
  LOBTypeName: string;
  Country_ID: number;
  City_ID: number;
  Landlord_Legal_Name: string;
  Upload_Contract: null;
  Commercial_Register: string;
  Tax_Id: string;
  Country_Name: string;
  District_Name: string;
  City_Name: string;
  CurrencyName: string;
  Terms: string;
  longitude: string;
  latitude: string;
  pg_total: number;

};
